export {
  CreateWikiSpaceSchema,
  UpdateWikiSpaceSchema,
  CreateWikiPageSchema,
  UpdateWikiPageSchema,
  MoveWikiPageSchema,
  WikiPageTreeQuerySchema,
  WikiPageVersionQuerySchema,
  CreateNamedVersionSchema,
  CreateWikiCommentSchema,
  UpdateWikiCommentSchema,
  WikiCommentQuerySchema,
  CreateWikiShareSchema,
  UpdateWikiShareSchema,
  ValidateWikiShareSchema,
} from "@pm/shared";
