/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedWorkspaceSlugRouteImport } from './routes/_authed/$workspaceSlug'
import { Route as AuthedWorkspaceSlugIndexRouteImport } from './routes/_authed/$workspaceSlug/index'
import { Route as AuthOidcCompleteRouteImport } from './routes/auth.oidc.complete'
import { Route as AuthedWorkspaceSlugTimeRouteImport } from './routes/_authed/$workspaceSlug/time'
import { Route as AuthedWorkspaceSlugSettingsRouteImport } from './routes/_authed/$workspaceSlug/settings'
import { Route as AuthedWorkspaceSlugMyTasksRouteImport } from './routes/_authed/$workspaceSlug/my-tasks'
import { Route as AuthedWorkspaceSlugKnowledgeRouteImport } from './routes/_authed/$workspaceSlug/knowledge'
import { Route as AuthedWorkspaceSlugDriveRouteImport } from './routes/_authed/$workspaceSlug/drive'
import { Route as AuthedWorkspaceSlugAdminRouteImport } from './routes/_authed/$workspaceSlug/admin'
import { Route as AuthedWorkspaceSlugTimeIndexRouteImport } from './routes/_authed/$workspaceSlug/time.index'
import { Route as AuthedWorkspaceSlugProjectsIndexRouteImport } from './routes/_authed/$workspaceSlug/projects/index'
import { Route as AuthedWorkspaceSlugTimeReportsRouteImport } from './routes/_authed/$workspaceSlug/time.reports'
import { Route as AuthedWorkspaceSlugProjectsProjectIdRouteImport } from './routes/_authed/$workspaceSlug/projects/$projectId'
import { Route as AuthedWorkspaceSlugProjectsProjectIdSettingsRouteImport } from './routes/_authed/$workspaceSlug/projects/$projectId/settings'
import { Route as AuthedWorkspaceSlugProjectsProjectIdListRouteImport } from './routes/_authed/$workspaceSlug/projects/$projectId/list'
import { Route as AuthedWorkspaceSlugProjectsProjectIdCalendarRouteImport } from './routes/_authed/$workspaceSlug/projects/$projectId/calendar'
import { Route as AuthedWorkspaceSlugProjectsProjectIdBoardRouteImport } from './routes/_authed/$workspaceSlug/projects/$projectId/board'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspaceSlugRoute = AuthedWorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkspaceSlugIndexRoute =
  AuthedWorkspaceSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkspaceSlugRoute,
  } as any)
const AuthOidcCompleteRoute = AuthOidcCompleteRouteImport.update({
  id: '/auth/oidc/complete',
  path: '/auth/oidc/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkspaceSlugTimeRoute = AuthedWorkspaceSlugTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AuthedWorkspaceSlugRoute,
} as any)
const AuthedWorkspaceSlugSettingsRoute =
  AuthedWorkspaceSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedWorkspaceSlugRoute,
  } as any)
const AuthedWorkspaceSlugMyTasksRoute =
  AuthedWorkspaceSlugMyTasksRouteImport.update({
    id: '/my-tasks',
    path: '/my-tasks',
    getParentRoute: () => AuthedWorkspaceSlugRoute,
  } as any)
const AuthedWorkspaceSlugKnowledgeRoute =
  AuthedWorkspaceSlugKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthedWorkspaceSlugRoute,
  } as any)
const AuthedWorkspaceSlugDriveRoute =
  AuthedWorkspaceSlugDriveRouteImport.update({
    id: '/drive',
    path: '/drive',
    getParentRoute: () => AuthedWorkspaceSlugRoute,
  } as any)
const AuthedWorkspaceSlugAdminRoute =
  AuthedWorkspaceSlugAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthedWorkspaceSlugRoute,
  } as any)
const AuthedWorkspaceSlugTimeIndexRoute =
  AuthedWorkspaceSlugTimeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkspaceSlugTimeRoute,
  } as any)
const AuthedWorkspaceSlugProjectsIndexRoute =
  AuthedWorkspaceSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthedWorkspaceSlugRoute,
  } as any)
const AuthedWorkspaceSlugTimeReportsRoute =
  AuthedWorkspaceSlugTimeReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthedWorkspaceSlugTimeRoute,
  } as any)
const AuthedWorkspaceSlugProjectsProjectIdRoute =
  AuthedWorkspaceSlugProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthedWorkspaceSlugRoute,
  } as any)
const AuthedWorkspaceSlugProjectsProjectIdSettingsRoute =
  AuthedWorkspaceSlugProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedWorkspaceSlugProjectsProjectIdRoute,
  } as any)
const AuthedWorkspaceSlugProjectsProjectIdListRoute =
  AuthedWorkspaceSlugProjectsProjectIdListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthedWorkspaceSlugProjectsProjectIdRoute,
  } as any)
const AuthedWorkspaceSlugProjectsProjectIdCalendarRoute =
  AuthedWorkspaceSlugProjectsProjectIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthedWorkspaceSlugProjectsProjectIdRoute,
  } as any)
const AuthedWorkspaceSlugProjectsProjectIdBoardRoute =
  AuthedWorkspaceSlugProjectsProjectIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthedWorkspaceSlugProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$workspaceSlug': typeof AuthedWorkspaceSlugRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/$workspaceSlug/admin': typeof AuthedWorkspaceSlugAdminRoute
  '/$workspaceSlug/drive': typeof AuthedWorkspaceSlugDriveRoute
  '/$workspaceSlug/knowledge': typeof AuthedWorkspaceSlugKnowledgeRoute
  '/$workspaceSlug/my-tasks': typeof AuthedWorkspaceSlugMyTasksRoute
  '/$workspaceSlug/settings': typeof AuthedWorkspaceSlugSettingsRoute
  '/$workspaceSlug/time': typeof AuthedWorkspaceSlugTimeRouteWithChildren
  '/auth/oidc/complete': typeof AuthOidcCompleteRoute
  '/$workspaceSlug/': typeof AuthedWorkspaceSlugIndexRoute
  '/$workspaceSlug/projects/$projectId': typeof AuthedWorkspaceSlugProjectsProjectIdRouteWithChildren
  '/$workspaceSlug/time/reports': typeof AuthedWorkspaceSlugTimeReportsRoute
  '/$workspaceSlug/projects/': typeof AuthedWorkspaceSlugProjectsIndexRoute
  '/$workspaceSlug/time/': typeof AuthedWorkspaceSlugTimeIndexRoute
  '/$workspaceSlug/projects/$projectId/board': typeof AuthedWorkspaceSlugProjectsProjectIdBoardRoute
  '/$workspaceSlug/projects/$projectId/calendar': typeof AuthedWorkspaceSlugProjectsProjectIdCalendarRoute
  '/$workspaceSlug/projects/$projectId/list': typeof AuthedWorkspaceSlugProjectsProjectIdListRoute
  '/$workspaceSlug/projects/$projectId/settings': typeof AuthedWorkspaceSlugProjectsProjectIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/$workspaceSlug/admin': typeof AuthedWorkspaceSlugAdminRoute
  '/$workspaceSlug/drive': typeof AuthedWorkspaceSlugDriveRoute
  '/$workspaceSlug/knowledge': typeof AuthedWorkspaceSlugKnowledgeRoute
  '/$workspaceSlug/my-tasks': typeof AuthedWorkspaceSlugMyTasksRoute
  '/$workspaceSlug/settings': typeof AuthedWorkspaceSlugSettingsRoute
  '/auth/oidc/complete': typeof AuthOidcCompleteRoute
  '/$workspaceSlug': typeof AuthedWorkspaceSlugIndexRoute
  '/$workspaceSlug/projects/$projectId': typeof AuthedWorkspaceSlugProjectsProjectIdRouteWithChildren
  '/$workspaceSlug/time/reports': typeof AuthedWorkspaceSlugTimeReportsRoute
  '/$workspaceSlug/projects': typeof AuthedWorkspaceSlugProjectsIndexRoute
  '/$workspaceSlug/time': typeof AuthedWorkspaceSlugTimeIndexRoute
  '/$workspaceSlug/projects/$projectId/board': typeof AuthedWorkspaceSlugProjectsProjectIdBoardRoute
  '/$workspaceSlug/projects/$projectId/calendar': typeof AuthedWorkspaceSlugProjectsProjectIdCalendarRoute
  '/$workspaceSlug/projects/$projectId/list': typeof AuthedWorkspaceSlugProjectsProjectIdListRoute
  '/$workspaceSlug/projects/$projectId/settings': typeof AuthedWorkspaceSlugProjectsProjectIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/$workspaceSlug': typeof AuthedWorkspaceSlugRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/_authed/$workspaceSlug/admin': typeof AuthedWorkspaceSlugAdminRoute
  '/_authed/$workspaceSlug/drive': typeof AuthedWorkspaceSlugDriveRoute
  '/_authed/$workspaceSlug/knowledge': typeof AuthedWorkspaceSlugKnowledgeRoute
  '/_authed/$workspaceSlug/my-tasks': typeof AuthedWorkspaceSlugMyTasksRoute
  '/_authed/$workspaceSlug/settings': typeof AuthedWorkspaceSlugSettingsRoute
  '/_authed/$workspaceSlug/time': typeof AuthedWorkspaceSlugTimeRouteWithChildren
  '/auth/oidc/complete': typeof AuthOidcCompleteRoute
  '/_authed/$workspaceSlug/': typeof AuthedWorkspaceSlugIndexRoute
  '/_authed/$workspaceSlug/projects/$projectId': typeof AuthedWorkspaceSlugProjectsProjectIdRouteWithChildren
  '/_authed/$workspaceSlug/time/reports': typeof AuthedWorkspaceSlugTimeReportsRoute
  '/_authed/$workspaceSlug/projects/': typeof AuthedWorkspaceSlugProjectsIndexRoute
  '/_authed/$workspaceSlug/time/': typeof AuthedWorkspaceSlugTimeIndexRoute
  '/_authed/$workspaceSlug/projects/$projectId/board': typeof AuthedWorkspaceSlugProjectsProjectIdBoardRoute
  '/_authed/$workspaceSlug/projects/$projectId/calendar': typeof AuthedWorkspaceSlugProjectsProjectIdCalendarRoute
  '/_authed/$workspaceSlug/projects/$projectId/list': typeof AuthedWorkspaceSlugProjectsProjectIdListRoute
  '/_authed/$workspaceSlug/projects/$projectId/settings': typeof AuthedWorkspaceSlugProjectsProjectIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/$workspaceSlug'
    | '/onboarding'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/share/$token'
    | '/verify-email/$token'
    | '/$workspaceSlug/admin'
    | '/$workspaceSlug/drive'
    | '/$workspaceSlug/knowledge'
    | '/$workspaceSlug/my-tasks'
    | '/$workspaceSlug/settings'
    | '/$workspaceSlug/time'
    | '/auth/oidc/complete'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/projects/$projectId'
    | '/$workspaceSlug/time/reports'
    | '/$workspaceSlug/projects/'
    | '/$workspaceSlug/time/'
    | '/$workspaceSlug/projects/$projectId/board'
    | '/$workspaceSlug/projects/$projectId/calendar'
    | '/$workspaceSlug/projects/$projectId/list'
    | '/$workspaceSlug/projects/$projectId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/onboarding'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/share/$token'
    | '/verify-email/$token'
    | '/$workspaceSlug/admin'
    | '/$workspaceSlug/drive'
    | '/$workspaceSlug/knowledge'
    | '/$workspaceSlug/my-tasks'
    | '/$workspaceSlug/settings'
    | '/auth/oidc/complete'
    | '/$workspaceSlug'
    | '/$workspaceSlug/projects/$projectId'
    | '/$workspaceSlug/time/reports'
    | '/$workspaceSlug/projects'
    | '/$workspaceSlug/time'
    | '/$workspaceSlug/projects/$projectId/board'
    | '/$workspaceSlug/projects/$projectId/calendar'
    | '/$workspaceSlug/projects/$projectId/list'
    | '/$workspaceSlug/projects/$projectId/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_authed/$workspaceSlug'
    | '/_authed/onboarding'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/share/$token'
    | '/verify-email/$token'
    | '/_authed/$workspaceSlug/admin'
    | '/_authed/$workspaceSlug/drive'
    | '/_authed/$workspaceSlug/knowledge'
    | '/_authed/$workspaceSlug/my-tasks'
    | '/_authed/$workspaceSlug/settings'
    | '/_authed/$workspaceSlug/time'
    | '/auth/oidc/complete'
    | '/_authed/$workspaceSlug/'
    | '/_authed/$workspaceSlug/projects/$projectId'
    | '/_authed/$workspaceSlug/time/reports'
    | '/_authed/$workspaceSlug/projects/'
    | '/_authed/$workspaceSlug/time/'
    | '/_authed/$workspaceSlug/projects/$projectId/board'
    | '/_authed/$workspaceSlug/projects/$projectId/calendar'
    | '/_authed/$workspaceSlug/projects/$projectId/list'
    | '/_authed/$workspaceSlug/projects/$projectId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
  AuthOidcCompleteRoute: typeof AuthOidcCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$workspaceSlug': {
      id: '/_authed/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof AuthedWorkspaceSlugRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$workspaceSlug/': {
      id: '/_authed/$workspaceSlug/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof AuthedWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/auth/oidc/complete': {
      id: '/auth/oidc/complete'
      path: '/auth/oidc/complete'
      fullPath: '/auth/oidc/complete'
      preLoaderRoute: typeof AuthOidcCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/$workspaceSlug/time': {
      id: '/_authed/$workspaceSlug/time'
      path: '/time'
      fullPath: '/$workspaceSlug/time'
      preLoaderRoute: typeof AuthedWorkspaceSlugTimeRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/_authed/$workspaceSlug/settings': {
      id: '/_authed/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof AuthedWorkspaceSlugSettingsRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/_authed/$workspaceSlug/my-tasks': {
      id: '/_authed/$workspaceSlug/my-tasks'
      path: '/my-tasks'
      fullPath: '/$workspaceSlug/my-tasks'
      preLoaderRoute: typeof AuthedWorkspaceSlugMyTasksRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/_authed/$workspaceSlug/knowledge': {
      id: '/_authed/$workspaceSlug/knowledge'
      path: '/knowledge'
      fullPath: '/$workspaceSlug/knowledge'
      preLoaderRoute: typeof AuthedWorkspaceSlugKnowledgeRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/_authed/$workspaceSlug/drive': {
      id: '/_authed/$workspaceSlug/drive'
      path: '/drive'
      fullPath: '/$workspaceSlug/drive'
      preLoaderRoute: typeof AuthedWorkspaceSlugDriveRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/_authed/$workspaceSlug/admin': {
      id: '/_authed/$workspaceSlug/admin'
      path: '/admin'
      fullPath: '/$workspaceSlug/admin'
      preLoaderRoute: typeof AuthedWorkspaceSlugAdminRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/_authed/$workspaceSlug/time/': {
      id: '/_authed/$workspaceSlug/time/'
      path: '/'
      fullPath: '/$workspaceSlug/time/'
      preLoaderRoute: typeof AuthedWorkspaceSlugTimeIndexRouteImport
      parentRoute: typeof AuthedWorkspaceSlugTimeRoute
    }
    '/_authed/$workspaceSlug/projects/': {
      id: '/_authed/$workspaceSlug/projects/'
      path: '/projects'
      fullPath: '/$workspaceSlug/projects/'
      preLoaderRoute: typeof AuthedWorkspaceSlugProjectsIndexRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/_authed/$workspaceSlug/time/reports': {
      id: '/_authed/$workspaceSlug/time/reports'
      path: '/reports'
      fullPath: '/$workspaceSlug/time/reports'
      preLoaderRoute: typeof AuthedWorkspaceSlugTimeReportsRouteImport
      parentRoute: typeof AuthedWorkspaceSlugTimeRoute
    }
    '/_authed/$workspaceSlug/projects/$projectId': {
      id: '/_authed/$workspaceSlug/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$workspaceSlug/projects/$projectId'
      preLoaderRoute: typeof AuthedWorkspaceSlugProjectsProjectIdRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRoute
    }
    '/_authed/$workspaceSlug/projects/$projectId/settings': {
      id: '/_authed/$workspaceSlug/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedWorkspaceSlugProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedWorkspaceSlugProjectsProjectIdRoute
    }
    '/_authed/$workspaceSlug/projects/$projectId/list': {
      id: '/_authed/$workspaceSlug/projects/$projectId/list'
      path: '/list'
      fullPath: '/$workspaceSlug/projects/$projectId/list'
      preLoaderRoute: typeof AuthedWorkspaceSlugProjectsProjectIdListRouteImport
      parentRoute: typeof AuthedWorkspaceSlugProjectsProjectIdRoute
    }
    '/_authed/$workspaceSlug/projects/$projectId/calendar': {
      id: '/_authed/$workspaceSlug/projects/$projectId/calendar'
      path: '/calendar'
      fullPath: '/$workspaceSlug/projects/$projectId/calendar'
      preLoaderRoute: typeof AuthedWorkspaceSlugProjectsProjectIdCalendarRouteImport
      parentRoute: typeof AuthedWorkspaceSlugProjectsProjectIdRoute
    }
    '/_authed/$workspaceSlug/projects/$projectId/board': {
      id: '/_authed/$workspaceSlug/projects/$projectId/board'
      path: '/board'
      fullPath: '/$workspaceSlug/projects/$projectId/board'
      preLoaderRoute: typeof AuthedWorkspaceSlugProjectsProjectIdBoardRouteImport
      parentRoute: typeof AuthedWorkspaceSlugProjectsProjectIdRoute
    }
  }
}

interface AuthedWorkspaceSlugTimeRouteChildren {
  AuthedWorkspaceSlugTimeReportsRoute: typeof AuthedWorkspaceSlugTimeReportsRoute
  AuthedWorkspaceSlugTimeIndexRoute: typeof AuthedWorkspaceSlugTimeIndexRoute
}

const AuthedWorkspaceSlugTimeRouteChildren: AuthedWorkspaceSlugTimeRouteChildren =
  {
    AuthedWorkspaceSlugTimeReportsRoute: AuthedWorkspaceSlugTimeReportsRoute,
    AuthedWorkspaceSlugTimeIndexRoute: AuthedWorkspaceSlugTimeIndexRoute,
  }

const AuthedWorkspaceSlugTimeRouteWithChildren =
  AuthedWorkspaceSlugTimeRoute._addFileChildren(
    AuthedWorkspaceSlugTimeRouteChildren,
  )

interface AuthedWorkspaceSlugProjectsProjectIdRouteChildren {
  AuthedWorkspaceSlugProjectsProjectIdBoardRoute: typeof AuthedWorkspaceSlugProjectsProjectIdBoardRoute
  AuthedWorkspaceSlugProjectsProjectIdCalendarRoute: typeof AuthedWorkspaceSlugProjectsProjectIdCalendarRoute
  AuthedWorkspaceSlugProjectsProjectIdListRoute: typeof AuthedWorkspaceSlugProjectsProjectIdListRoute
  AuthedWorkspaceSlugProjectsProjectIdSettingsRoute: typeof AuthedWorkspaceSlugProjectsProjectIdSettingsRoute
}

const AuthedWorkspaceSlugProjectsProjectIdRouteChildren: AuthedWorkspaceSlugProjectsProjectIdRouteChildren =
  {
    AuthedWorkspaceSlugProjectsProjectIdBoardRoute:
      AuthedWorkspaceSlugProjectsProjectIdBoardRoute,
    AuthedWorkspaceSlugProjectsProjectIdCalendarRoute:
      AuthedWorkspaceSlugProjectsProjectIdCalendarRoute,
    AuthedWorkspaceSlugProjectsProjectIdListRoute:
      AuthedWorkspaceSlugProjectsProjectIdListRoute,
    AuthedWorkspaceSlugProjectsProjectIdSettingsRoute:
      AuthedWorkspaceSlugProjectsProjectIdSettingsRoute,
  }

const AuthedWorkspaceSlugProjectsProjectIdRouteWithChildren =
  AuthedWorkspaceSlugProjectsProjectIdRoute._addFileChildren(
    AuthedWorkspaceSlugProjectsProjectIdRouteChildren,
  )

interface AuthedWorkspaceSlugRouteChildren {
  AuthedWorkspaceSlugAdminRoute: typeof AuthedWorkspaceSlugAdminRoute
  AuthedWorkspaceSlugDriveRoute: typeof AuthedWorkspaceSlugDriveRoute
  AuthedWorkspaceSlugKnowledgeRoute: typeof AuthedWorkspaceSlugKnowledgeRoute
  AuthedWorkspaceSlugMyTasksRoute: typeof AuthedWorkspaceSlugMyTasksRoute
  AuthedWorkspaceSlugSettingsRoute: typeof AuthedWorkspaceSlugSettingsRoute
  AuthedWorkspaceSlugTimeRoute: typeof AuthedWorkspaceSlugTimeRouteWithChildren
  AuthedWorkspaceSlugIndexRoute: typeof AuthedWorkspaceSlugIndexRoute
  AuthedWorkspaceSlugProjectsProjectIdRoute: typeof AuthedWorkspaceSlugProjectsProjectIdRouteWithChildren
  AuthedWorkspaceSlugProjectsIndexRoute: typeof AuthedWorkspaceSlugProjectsIndexRoute
}

const AuthedWorkspaceSlugRouteChildren: AuthedWorkspaceSlugRouteChildren = {
  AuthedWorkspaceSlugAdminRoute: AuthedWorkspaceSlugAdminRoute,
  AuthedWorkspaceSlugDriveRoute: AuthedWorkspaceSlugDriveRoute,
  AuthedWorkspaceSlugKnowledgeRoute: AuthedWorkspaceSlugKnowledgeRoute,
  AuthedWorkspaceSlugMyTasksRoute: AuthedWorkspaceSlugMyTasksRoute,
  AuthedWorkspaceSlugSettingsRoute: AuthedWorkspaceSlugSettingsRoute,
  AuthedWorkspaceSlugTimeRoute: AuthedWorkspaceSlugTimeRouteWithChildren,
  AuthedWorkspaceSlugIndexRoute: AuthedWorkspaceSlugIndexRoute,
  AuthedWorkspaceSlugProjectsProjectIdRoute:
    AuthedWorkspaceSlugProjectsProjectIdRouteWithChildren,
  AuthedWorkspaceSlugProjectsIndexRoute: AuthedWorkspaceSlugProjectsIndexRoute,
}

const AuthedWorkspaceSlugRouteWithChildren =
  AuthedWorkspaceSlugRoute._addFileChildren(AuthedWorkspaceSlugRouteChildren)

interface AuthedRouteChildren {
  AuthedWorkspaceSlugRoute: typeof AuthedWorkspaceSlugRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedWorkspaceSlugRoute: AuthedWorkspaceSlugRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
  AuthOidcCompleteRoute: AuthOidcCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
